name = "bot_listener_webhook" # todo
main = "./src/webhookListen.ts"
compatibility_date = "2022-05-03"

# this is used to set all the required endpoint to map between dominic and CF worker
[vars]
DOWNLOAD_FILE = "downloadfile"
LIST_STORAGE_VOLUME = "listfiles"
DOWNLOAD_STATS = "downloads"
PAUSEALL_DOWNLOADS = "pauseAll"
DOM_ENDPOINT = "askdom"

# The necessary secrets are:
# - CHATID
# - TELEGRAM_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these

[triggers]
crons = ["0 0 * * *"]